### PR TITLE
Distributed Crawling -- Non-API Run

### PR DESCRIPTION
**Pull request by gsangiolo**
The purpose of this branch is to allow us to run a full crawl of the 7k charter school list while navigating around the various roadblock urls.

This new branch uses Docker to split a list of urls into 100-line chunks, then runs each chunk in parallel using Python's multiprocessing package.

To test:
Follow the directions in the README!
1. Run Mongo
2. From scrapy/schools, run "docker build . -t schoolcrawler"
3. Run "docker ps" to get the id of the created container
4. Run "docker run --network='host' containerid"
5. Follow the logs (they terminate randomly, but the spider is still running): docker logs containerid --follow
6. Check Mongo: docker exec -it mongodb bash, mongo -u username -p password, show dbs
7. See how much data you can get!

### CODE REVIEW

**Review by pmasaya — APPROVED** [review]
Nicely done!

**Comment by pmasaya** [comment]
**This branch is NOT meant to merge with master, in fact this branch is DEPRECATED. But it has enduring value and but could still be useful for crawling through tons of URLs (rather than an API setup), i.e. a one-off data grab.
The distributed crawl structure of this branch (using mapReduce) is built into the related Flaskify branch (now merged into master). The run school spider file in both branches splits files and then multithreads functions.**

**Comment by jhaber-zz** [comment]
*Step 0*: Confirm that line ~110 of scrapy/schools/schools/settings.py is 
MONGO_URI = 'mongodb://localhost:27000' 

*Updated step 1*: docker run -d --name mongodb -p 27000:27017 --restart always --log-opt max-size=500m -e MONGO_INITDB_ROOT_USERNAME=name_here -e MONGO_INITDB_ROOT_PASSWORD=pw_here -v /vol_b/data/mongodata:/data/db mongo

*Updated step 3*: docker run --network='host' --restart always --log-opt max-size=500m -v /vol_b/data/sc_data/scrapy:/schools container_id

**Comment by jhaber-zz** [comment]
This code got merged into [the more recent PR ](https://github.com/URAP-charter/web_scraping/pull/33#issue-1099767266) and merged with master.

**Pull request closed without merging**
